default:
  maxPlayers: 4

maps:
  1:
    spawns:
      0:
        x: 256
        y: 60
        z: 256
        yaw: 0
        pitch: 0
      1:
        x: 64
        y: 60
        z: 64
        yaw: 180
        pitch: 0
  2:
    spawns:
      0:
        x: 192
        y: 60
        z: 192
        yaw: 90
        pitch: 0
      1:
        x: 128
        y: 60
        z: 128
        yaw: 270
        pitch: 0
  3:
    spawns:
      0:
        x: 92
        y: 60
        z: 92
        yaw: 45
        pitch: 0
      1:
        x: 240
        y: 60
        z: 240
        yaw: 225
        pitch: 0

modes:
  0:
    name: "PVP"
    enabled: true
    duration: 60
    maps:
      - 1
      - 2
      - 3