default:
  maxPlayers: 4
  pointsGoal: 10.0

maps:
  1:
    spawns:
      0:
        x: 256
        y: 60
        z: 256
        yaw: 0
        pitch: 0
      1:
        x: 64
        y: 60
        z: 64
        yaw: 180
        pitch: 0
  2:
    meta:
      ventilator: true
    spawns:
      0:
        x: 192
        y: 60
        z: 192
        yaw: 90
        pitch: 0
      1:
        x: 128
        y: 60
        z: 128
        yaw: 270
        pitch: 0