default:
  enabled: true
  duration: 120
  displayName: Столбы удачи
  description: Получай случайные предметы и убей своего противника, пока вы оба стоите на двух столбах!
  maps:
    - 3

meta:
  interval: 1.2
  items:
    - "STONE_SWORD"
    - "IRON_SWORD"
    - "DIAMOND_SWORD"

    - "WOODEN_AXE"
    - "DIAMOND_AXE"
    - "MACE"

    - "BOW"
    - "CROSSBOW"

    - "ARROW"
    - "SPECTRAL_ARROW"

    - "GOLDEN_APPLE"
    - "ENCHANTED_GOLDEN_APPLE"

    - "COOKED_BEEF"
    - "COOKED_PORKCHOP"
    - "COOKED_CHICKEN"
    - "COOKED_SALMON"
    - "BREAD"
    - "BAKED_POTATO"
    - "GOLDEN_CARROT"

    - "ENDER_PEARL"
    - "WIND_CHARGE"

    - "TNT"
    - "FLINT_AND_STEEL"

    - "FISHING_ROD"

    - "LEATHER_HELMET"
    - "LEATHER_CHESTPLATE"
    - "LEATHER_LEGGINGS"
    - "LEATHER_BOOTS"

    - "CHAINMAIL_HELMET"
    - "CHAINMAIL_CHESTPLATE"
    - "CHAINMAIL_LEGGINGS"
    - "CHAINMAIL_BOOTS"

    - "IRON_HELMET"
    - "IRON_CHESTPLATE"
    - "IRON_LEGGINGS"
    - "IRON_BOOTS"

    - "GOLDEN_HELMET"
    - "GOLDEN_CHESTPLATE"
    - "GOLDEN_LEGGINGS"
    - "GOLDEN_BOOTS"

    - "DIAMOND_HELMET"
    - "DIAMOND_CHESTPLATE"
    - "DIAMOND_LEGGINGS"
    - "DIAMOND_BOOTS"

    - "NETHERITE_HELMET"
    - "NETHERITE_CHESTPLATE"
    - "NETHERITE_LEGGINGS"
    - "NETHERITE_BOOTS"

    - "TOTEM_OF_UNDYING"

    - "COBWEB"

    - "DIRT"
    - "OAK_LOG"
    - "SPRUCE_LOG"
    - "MANGROVE_LOG"
    - "WHITE_STAINED_GLASS"
    - "MAGENTA_STAINED_GLASS"
    - "SLIME_BLOCK"
    - "RED_BED"
    - "WATER_BUCKET"