name: ${NAME}
version: ${VERSION}
api-version: ${MINECRAFT_VERSION}
main: ru.joutak.adhd.ADHDPlugin
description: 'The ADHD minigame plugin'
authors: ['EnderDissa', 'Ga_Mes', 'e__lm']
contributors: []
website: ${WEBSITE}

depend: []
softdepend: ['PlaceholderAPI']
libraries:
  - 'org.jetbrains.kotlin:kotlin-stdlib:${KOTLIN_VERSION}'
